---
- name: Развернуть веб-приложение на подчиненной машине
  hosts: web
  tasks:
    - name: Установить nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Скопировать страницу приложения
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Запустить nginx
      service:
        name: nginx
        state: started
        enabled: yes
